# Generated by Django 3.2.5 on 2021-07-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0004_alter_usuarios_id'),
        ('Categorias', '0003_alter_categorias_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('detalle', models.CharField(max_length=250)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('precio', models.BigIntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categorias')),
                ('usuarios', models.ManyToManyField(to='Usuarios.Usuarios')),
            ],
        ),
    ]
