# Generated by Django 3.2.5 on 2021-07-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
