# Generated by Django 3.1.5 on 2021-07-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_productos_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
