# Generated by Django 3.2.5 on 2021-07-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20210722_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
