# Generated by Django 3.2.5 on 2021-07-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuarios_email'),
        ('Productos', '0003_auto_20210722_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Usuarios',
            field=models.ManyToManyField(to='Usuarios.Usuarios'),
        ),
    ]
