# Generated by Django 3.2.5 on 2021-07-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_productos_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='Usuarios',
            new_name='usuarios',
        ),
    ]
