# Generated by Django 3.2.5 on 2021-07-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
        ('Productos', '0005_rename_usuarios_productos_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ManyToManyField(to='Proveedor.Proveedor'),
        ),
    ]
