# Generated by Django 3.2.5 on 2021-07-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_auto_20210723_1648'),
        ('Productos', '0006_productos_proveedor'),
    ]

    operations = [
    ]
