# Generated by Django 3.2.5 on 2021-07-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=20)),
                ('nit', models.IntegerField(null=True)),
                ('telefono', models.IntegerField(null=True)),
            ],
        ),
    ]
