# Generated by Django 3.2.5 on 2021-07-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_usuarios_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Usuarios',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
