# Generated by Django 3.2.5 on 2021-07-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_alter_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.BigIntegerField(null=True),
        ),
    ]
