# Generated by Django 3.2.5 on 2021-07-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_usuarios_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
    ]
