# Generated by Django 3.1.5 on 2021-07-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_remove_usuarios_last_login'),
        ('Usuarios', '0005_auto_20210724_0141'),
    ]

    operations = [
    ]
