# Generated by Django 3.2.5 on 2021-07-26 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20210724_0141'),
        ('Usuarios', '0012_remove_usuarios_last_login'),
    ]

    operations = [
    ]
