# Generated by Django 3.1.5 on 2021-07-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0013_merge_20210725_1757'),
        ('Usuarios', '0013_merge_20210725_1905'),
    ]

    operations = [
    ]
