# Generated by Django 3.1.5 on 2021-07-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0014_merge_20210725_1908'),
        ('Usuarios', '0014_alter_usuarios_id'),
    ]

    operations = [
    ]
